spring.application.name=auth-service
server.port=9001

spring.cloud.refresh.enabled=false
# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/hms_auth_db
spring.datasource.username=root
spring.datasource.password=Ish983556
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

auth.admin.email=admin@hotelbooking.com
auth.admin.password=admin123
auth.admin.full-name=System Admin

auth.jwt.secret=super-secret-key-change-later-1234567890
auth.jwt.expiry-minutes=60

# Redis Cache
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=300000
